spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
        provider:
          kakao:
            # 프론트에서 소셜 로그인 버튼을 누르면 백엔드로 요청이 오고, 백엔드에서는 이 주소를 리턴
            authorization-uri: https://kauth.kakao.com/oauth/authorize?prompt=login
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  cloud:
    azure:
      cosmos:
        endpoint: ${COSMOS_URI}
        key: ${COSMOS_KEY}
        database: ${COSMOS_DATABASE}
        container: ${PRODUCT_CONTAINER_NAME}
jwt:
  secret:
    key: ${JWT_SECRET_KEY}

openai:
  endpoint: ${MODEL_ENDPOINT}
  apiKey: ${MODEL_API_KEY}

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG